import { JUP_LIMIT_ORDER_PROGRAM_PK, JUP_SWAP_PROGRAM_PK, MARGINFY_PROGRAM_PK, ORCA_PROGRAM_PK } from "./constants.js";

enum ProcessorType {

  JUP_SWAP_PARSER = JUP_SWAP_PROGRAM_PK,
  
  JUP_LIMIT_ORDER_PARSER = JUP_LIMIT_ORDER_PROGRAM_PK,

  MARGINFY_PARSER = MARGINFY_PROGRAM_PK,

  ORCA_PARSER = ORCA_PROGRAM_PK,

  UNKNOWN = undefined
}

export default ProcessorType
